#!/bin/bash
mkdir -p ../editor/levels && \
rm -f ../editor/levels/*.xcf.png && \
rm -f ../editor/levels/*.xcf-ladders.png && \
rm -f ../editor/levels/*.xcf-entities.png && \
rm -f ../editor/levels/*.xcf.png.inc && \
rm -f ../editor/levels/num_levels.inc && \
rm -f ../editor/levels/level_offsets.inc && \
cd ../data/levels && \
../../default/gimp-xcf2png && \
mv *.png ../../editor/levels/. && \
cd ../../editor && \
make clean && \
make && \
./png2inc && \
cd ../data && \
../../../bin/gconvert tileset.xml && \
../../../bin/gconvert sprites.xml && \
cd ../default && \
make clean && \
make && \
../../../bin/uzem -c bugz.hex
