#!/bin/sh
cd ../editor && \
make clean && \
make && \
./png2inc && \
cd ../data && \
~/uzebox/bin/gconvert_allow_dupes tileset.xml && \
~/uzebox/bin/gconvert sprites.xml && \
cd ../default && \
make clean && \
make && \
~/uzebox/bin/uzem -f -c physics.hex
